# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box		= "centos7.1"
  config.vm.hostname	= "rails-tutorial"
  
  # VM の設定を変更する
  # メモリ: 2GiB
  # CPU: 1
  config.vm.provider :virtualbox do |vbox|
	vbox.customize [ "modifyvm", :id, "--memory", 2048, "--cpus", "1" ]
	vbox.name = "rail-tutorial"
  end
  
  # 共有ディレクトリ
  config.vm.synced_folder "../../workspace", "/var/www/workspace"
  
  # network
  config.vm.network "private_network", ip: "192.168.33.10"
  
  ## Provision ####
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./site.yml"
    ansible.verbose = "vv"
    ansible.tags = [
      "common",
      "ruby",
      "rails",
      "app"
    ]
  end 

end
