---
# よく使うコマンドをインストールしておく
- name: install basic command
  sudo: yes
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - openssl-devel
    - readline-devel
    - zlib-devel

# 開発中は何かと邪魔になるのでfirewalldは止めておく
- name: stop firewalld
  sudo: yes
  service: 
    name: firewalld
    enabled: no
    state: stopped

